namespace VbaDev.Cli;

internal static class PowerShellCompletionScriptRenderer
{
    public static string Render(string generatingExecutablePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(generatingExecutablePath);
        var executablePath = Path.GetFullPath(generatingExecutablePath);
        var executableLiteral = ToSingleQuotedString(executablePath);
        return string.Join(
            Environment.NewLine,
            $"$vbaDevExecutable = {executableLiteral}",
            "Register-ArgumentCompleter -Native " +
            "-CommandName @('vba-dev', 'vba-dev.exe', $vbaDevExecutable) " +
            "-ScriptBlock {",
            "    param($wordToComplete, $commandAst, $cursorPosition)",
            string.Empty,
            $"    $vbaDevExecutable = {executableLiteral}",
            "    if ($null -eq $commandAst -or $commandAst.CommandElements.Count -eq 0) { return }",
            string.Empty,
            "    $commandElement = $commandAst.CommandElements[0]",
            "    $commandLineText = $commandAst.Extent.Text",
            "    $commandOffset = $commandAst.Extent.StartOffset",
            "    $argumentOffset = $commandElement.Extent.EndOffset - $commandOffset",
            "    if ($argumentOffset -lt 0 -or $argumentOffset -gt $commandLineText.Length) { return }",
            string.Empty,
            "    $completionFilterPrefix = $null",
            "    $requiresPrefixFilter = $false",
            "    $currentElement = $null",
            "    foreach ($element in $commandAst.CommandElements) {",
            "        if ($element -eq $commandElement) { continue }",
            "        if ($element.Extent.StartOffset -le $cursorPosition -and",
            "            $cursorPosition -le $element.Extent.EndOffset) {",
            "            $currentElement = $element",
            "        }",
            "    }",
            string.Empty,
            "    $transport = [System.Text.StringBuilder]::new()",
            "    $completionCursor = $null",
            "    foreach ($element in $commandAst.CommandElements) {",
            "        if ($element -eq $commandElement) { continue }",
            "        $valueProperty = $element.PSObject.Properties['Value']",
            "        if ($element -eq $currentElement -and $null -ne $valueProperty) {",
            "            if ($cursorPosition -ge $currentElement.Extent.EndOffset) {",
            "                $completionFilterPrefix = [string]$valueProperty.Value",
            "            }",
            "            else {",
            "                $rawPrefixOffset = $currentElement.Extent.StartOffset - $commandOffset",
            "                $rawPrefixLength = $cursorPosition - $currentElement.Extent.StartOffset",
            "                $completionFilterPrefix = $commandLineText.Substring(",
            "                    $rawPrefixOffset,",
            "                    $rawPrefixLength)",
            "                if ($completionFilterPrefix.StartsWith(\"'\", [StringComparison]::Ordinal)) {",
            "                    $completionFilterPrefix = $completionFilterPrefix.Substring(1).Replace(\"''\", \"'\")",
            "                }",
            "                elseif ($completionFilterPrefix.StartsWith('" + "\"" + "', [StringComparison]::Ordinal)) {",
            "                    $completionFilterPrefix = $completionFilterPrefix.Substring(1) -replace '`(.)', '$1'",
            "                }",
            "            }",
            "            $transportToken = ($completionFilterPrefix -split '\\s+', 2)[0]",
            "            $requiresPrefixFilter = ![string]::Equals(",
            "                $transportToken,",
            "                $completionFilterPrefix,",
            "                [StringComparison]::Ordinal)",
            "        }",
            "        elseif ($null -ne $valueProperty) {",
            "            $transportToken = [string]$valueProperty.Value",
            "            $transportToken = $transportToken.Replace('\\', '/')",
            "            if ($transportToken -match '\\s') {",
            "                if ($PSVersionTable.PSVersion.Major -le 5) {",
            "                    $transportToken = '\\\"' + $transportToken.Replace('\"', '\\\"') + '\\\"'",
            "                }",
            "                else {",
            "                    $transportToken = '\"' + $transportToken.Replace('\"', '\"\"') + '\"'",
            "                }",
            "            }",
            "        }",
            "        else {",
            "            $transportToken = $element.Extent.Text.Replace('\\', '/')",
            "        }",
            "        $cursorPrecedesElement = $null -eq $currentElement -and",
            "            $null -eq $completionCursor -and",
            "            $cursorPosition -le $element.Extent.StartOffset",
            "        if ($transport.Length -gt 0) {",
            "            [void]$transport.Append(' ')",
            "            if ($cursorPrecedesElement) {",
            "                $completionCursor = $transport.Length",
            "                [void]$transport.Append(' ')",
            "            }",
            "        }",
            "        elseif ($cursorPrecedesElement) {",
            "            $completionCursor = 0",
            "            [void]$transport.Append(' ')",
            "        }",
            "        $tokenStart = $transport.Length",
            "        [void]$transport.Append($transportToken)",
            "        if ($element -eq $currentElement) {",
            "            $completionCursor = $tokenStart + $transportToken.Length",
            "        }",
            "    }",
            "    $completionCommandLine = $transport.ToString()",
            "    if ($null -eq $completionCursor) {",
            "        $lastElement = $commandAst.CommandElements[$commandAst.CommandElements.Count - 1]",
            "        $completionCursor = $completionCommandLine.Length",
            "        if ($cursorPosition -gt $lastElement.Extent.EndOffset) {",
            "            $completionCursor++",
            "        }",
            "    }",
            string.Empty,
            "    $suggestDirective = \"[suggest:$completionCursor]\"",
            "    try {",
            "        $suggestions = @(& $vbaDevExecutable $suggestDirective $completionCommandLine 2>$null)",
            "    }",
            "    catch {",
            "        return",
            "    }",
            "    if ($LASTEXITCODE -ne 0) { return }",
            string.Empty,
            "    foreach ($suggestion in $suggestions) {",
            "        if ([string]::IsNullOrEmpty($suggestion)) { continue }",
            "        if ($requiresPrefixFilter -and " +
            "!$suggestion.StartsWith($completionFilterPrefix, [StringComparison]::OrdinalIgnoreCase)) { continue }",
            "        $completionText = \"'\" + $suggestion.Replace(\"'\", \"''\") + \"'\"",
            "        [System.Management.Automation.CompletionResult]::new(",
            "            $completionText,",
            "            $suggestion,",
            "            [System.Management.Automation.CompletionResultType]::ParameterValue,",
            "            $suggestion)",
            "    }",
            "}",
            string.Empty);
    }

    private static string ToSingleQuotedString(string value)
        => $"'{value.Replace("'", "''", StringComparison.Ordinal)}'";
}
